services:
  jenkins:
    build: ./jenkins
    container_name: jenkins-server
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - jenkins-network
    restart: unless-stopped

  test-app:
    build: ./app
    container_name: test-environment
    ports:
      - "5000:5000"
    networks:
      - jenkins-network
    depends_on:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge