version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    ports:
      - "8081:8080"       # Jenkins UI
      - "5001:5001"     # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Allow Jenkins to talk to Docker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - jenkins-network
    restart: unless-stopped

  test-app:
    build:
      context: ./app
    container_name: test-environment
    ports:
      - "5000:5000"       # Expose Flask app
    networks:
      - jenkins-network
    depends_on:
      - jenkins
    restart: unless-stopped

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge
